// src/api/packagesData.js
export default [
    // 1. 드라마 - 갯마을 차차차
    {
        contents: '드라마',
        title: '갯마을 차차차',
        subtitle: '포항 구룡포·청진항 패키지',
        subtitle2: '포항 구룡포·청진항',
        desc: '잔잔한 바닷마을 풍경 속, 드라마 속 힐링 장소를 직접 걸어보는 여행',
        backgroundImg: '/images/tour/main/guryongpo-bg.png',
        posterImg: '/images/tour/main/chachacha.png',
        thumbImg: '/images/tour/main/chachacha_thumb.png',
        benefits: [
            { icon: 'walk', text: '바닷마을 산책' },
            { icon: 'cafe', text: '핫플 카페 2곳' },
            { icon: 'map', text: '로케 지도 제공' },
            { icon: 'bus', text: '왕복 셔틀' },
        ],
        slug: 'hometown-chachacha-tour',
        date: '상시출발',
        duration: '2박 3일',
        nights: 2,
        days: 3,
        flight: 'KTX 왕복',
        shopping: '자유쇼핑 가능',
        guide_fee: '포함',
        optional: false,
        adult_fee: 390000,
        child_fee: 350000,
        // ✅ 오늘 기준으로 매일 출발
        schedule: { freq: 'DAILY' },
    },

    // 2. 예능 - 윤식당
    {
        contents: '예능',
        title: '윤식당 2',
        subtitle: '스페인 테네리페 패키지',
        subtitle2: '스페인 테네리페',
        desc: '태양의 섬에서 예능 속 따뜻한 분위기를 그대로 경험하는 휴양 여행',
        backgroundImg: '/images/tour/main/tenerife-bg.png',
        posterImg: '/images/tour/main/younskitchen2.png',
        thumbImg: '/images/tour/main/younskitchen2_thumb.png',
        benefits: [
            { icon: 'calendar', text: '6박 8일' },
            { icon: 'airplane', text: '왕복 항공권' },
            { icon: 'hotel', text: '4성급 호텔' },
            { icon: 'food', text: '조식 포함' },
        ],
        slug: 'younskitchen2-tenerife',
        date: '출발일 지정',
        duration: '3박 4일',
        nights: 3,
        days: 4,
        flight: '대한항공 직항',
        shopping: '현지 자유시간 포함',
        guide_fee: '포함',
        optional: true,
        adult_fee: 1390000,
        child_fee: 1200000,
        // 필요 시 departures: ['2025-11-05','2025-11-12'] 같이 고정일을 넣어도 됩니다.
    },

    // 3. 드라마 - 폭싹 속았수다
    {
        contents: '드라마',
        title: '폭싹 속았수다',
        subtitle: '고창 청보리밭 패키지',
        subtitle2: '고창 청보리밭',
        desc: '푸른 청보리밭 사이로 드라마 속 명장면을 재현하는 힐링 로드',
        backgroundImg: '/images/tour/main/jeju-bg.png',
        posterImg: '/images/tour/main/tangerines.png',
        thumbImg: '/images/tour/main/tangerines_thumb.png',
        benefits: [
            { icon: 'calendar', text: '2박 3일' },
            { icon: 'hotel', text: '부티크호텔' },
            { icon: 'food', text: '조식 2회' },
            { icon: 'ticket', text: '입장권 포함' },
        ],
        slug: 'when-life-gives-you-tangerines',
        date: '상시출발',
        duration: '2박 3일',
        nights: 2,
        days: 3,
        flight: '김포-제주 왕복',
        shopping: '자유쇼핑 가능',
        guide_fee: '포함',
        optional: false,
        adult_fee: 420000,
        child_fee: 380000,
        // ✅ 오늘 기준으로 매일 출발
        schedule: { freq: 'DAILY' },
    },

    // 4. 영화 - 범죄도시4
    {
        contents: '영화',
        title: '범죄도시 4',
        subtitle: '필리핀 보홀 섬 패키지',
        subtitle2: '필리핀 보홀 섬',
        desc: '액션 영화 촬영 현장의 열기를 느낄 수 있는 남국의 섬 여행',
        backgroundImg: '/images/tour/main/bohol-bg.png',
        posterImg: '/images/tour/main/crimecity4.png',
        thumbImg: '/images/tour/main/crimecity4_thumb.png',
        benefits: [
            { icon: 'calendar', text: '3박 5일' },
            { icon: 'airplane', text: '대한항공' },
            { icon: 'shopping', text: '쇼핑 3회' },
            { icon: 'dollar', text: '가이드 $60' },
            { icon: 'flag', text: '선택 관광' },
        ],
        slug: 'crimecity4-bohol-tour',
        date: '출발일 지정',
        duration: '3박 5일',
        nights: 3,
        days: 5,
        flight: '대한항공',
        shopping: '쇼핑 3회 포함',
        guide_fee: '$60',
        optional: true,
        adult_fee: 1590000,
        child_fee: 1390000,
        // 필요 시 schedule 또는 departures를 추가
    },

    // 5. K-POP - BTS
    {
        contents: 'K-POP',
        title: 'BTS',
        subtitle: '콘서트/뮤직비디오 패키지',
        subtitle2: '콘서트/뮤직비디오',
        desc: 'BTS가 다녀간 뮤비/공연 장소를 따라가는 팬 성지순례 투어',
        backgroundImg: '/images/tour/main/bts-bg.png',
        posterImg: '/images/tour/main/bts-yet-to-come.png',
        thumbImg: '/images/tour/main/bts_thumb.png',
        benefits: [
            { icon: 'calendar', text: '2박 3일' },
            { icon: 'ticket', text: '영화 관람 포함' },
            { icon: 'hotel', text: '특급호텔' },
            { icon: 'tourbus', text: 'BTS 성지 투어' },
        ],
        slug: 'bts-yet-to-come-tour',
        date: '일정 고정 (1~6명)',
        duration: '2박 3일',
        nights: 2,
        days: 3,
        flight: 'KTX/항공',
        shopping: '자유 쇼핑 가능',
        guide_fee: '포함',
        optional: false,
        adult_fee: 650000,
        child_fee: 600000,
    },

    // 6. K-POP - BLACKPINK
    {
        contents: 'K-POP',
        title: 'BLACKPINK',
        subtitle: '콘서트/뮤직비디오 패키지',
        subtitle2: '콘서트/뮤직비디오',
        desc: '글로벌 스타 블랙핑크의 무대와 뮤비 촬영지를 직접 방문하는 특별한 투어',
        backgroundImg: '/images/tour/main/blackpink-bg.png',
        posterImg: '/images/tour/main/blackpink.png',
        thumbImg: '/images/tour/main/blackpink_thumb.png',
        benefits: [
            { icon: 'calendar', text: '2박 3일' },
            { icon: 'hotel', text: '5성급 호텔' },
            { icon: 'ticket', text: '콘서트 티켓 포함' },
            { icon: 'shopping', text: '굿즈샵 투어' },
        ],
        slug: 'blackpink-worldtour-seoul',
        date: '일정 고정 (1~6명)',
        duration: '2박 3일',
        nights: 2,
        days: 3,
        flight: '서울 집결',
        shopping: '굿즈샵 포함',
        guide_fee: '포함',
        optional: false,
        adult_fee: 580000,
        child_fee: 540000,
    },

    // 7. 예능 - 서진이네
    {
        contents: '예능',
        title: '서진이네 2',
        subtitle: '멕시코 바칼라르 패키지',
        subtitle2: '멕시코 바칼라르',
        desc: '청량한 호수 위 수상 하우스에서 즐기는 느긋한 힐링 투어',
        backgroundImg: '/images/tour/main/bacalar-bg.png',
        posterImg: '/images/tour/main/seojin.png',
        thumbImg: '/images/tour/main/seojin_thumb.png',
        benefits: [
            { icon: 'calendar', text: '4박 6일' },
            { icon: 'boat', text: '라군 보트 투어' },
            { icon: 'food', text: '로컬 맛집 3회' },
            { icon: 'camera', text: '촬영 포인트 방문' },
        ],
        slug: 'seojin-mexico-bacalar',
        date: '출발일 지정',
        duration: '3박 4일',
        nights: 3,
        days: 4,
        flight: '대한항공 + 멕시코 국내선',
        shopping: '현지 마켓 투어 포함',
        guide_fee: '포함',
        optional: true,
        adult_fee: 1990000,
        child_fee: 1790000,
    },

    // 8. 영화 - 하얼빈
    {
        contents: '영화',
        title: '하얼빈',
        subtitle: '몽골 고비사막 패키지',
        subtitle2: '몽골 고비사막',
        desc: '광활한 고비사막에서 영화 속 장면처럼 낙타 트래킹을 즐기는 이색 투어',
        backgroundImg: '/images/tour/main/harbin-bg.png',
        posterImg: '/images/tour/main/harbin.png',
        thumbImg: '/images/tour/main/harbin_thumb.png',
        benefits: [
            { icon: 'calendar', text: '3박 4일' },
            { icon: 'hotel', text: '특급호텔' },
            { icon: 'plane', text: '항공 포함' },
            { icon: 'gift', text: '기념품 증정' },
        ],
        slug: 'harbin-film-tour',
        date: '매주 월요일 출발',
        duration: '3박 4일',
        nights: 3,
        days: 4,
        flight: '대한항공 직항',
        shopping: '자유 쇼핑 가능',
        guide_fee: '포함',
        optional: false,
        adult_fee: 1290000,
        child_fee: 1090000,
        // ✅ 오늘 기준 매주 월요일 출발
        schedule: { freq: 'WEEKLY', byWeekday: ['MO'] },
    },
];
